[build]
# target = "riscv32imc-esp-espidf" # esp32c3
target = "riscv32imac-esp-espidf" # esp32c6

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash.exe flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash.exe flash --monitor"

# https://github.com/esp-rs/esp-idf-sys/issues/275
rustflags = ["--cfg", "espidf_time64", "--codegen", "force-unwind-tables=yes"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# MCU = "esp32c3"
MCU = "esp32c6"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.3.2"
